### ISSUE TITLE
Issue running on Ubuntu/macOS

### ISSUE THREAD

**Issue by garygrossgarten** [kaito1410/AutoDD_Rev2#15]
Hey there,

I'm getting the following error trying to run the main.py on both Ubuntu and macOS.

```
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    main()
  File "main.py", line 98, in main
    print_tbl(results_tbl, args.filename, args.allsub, args.yahoo, args.csv)
  File "/app/auto-dd/AutoDD.py", line 378, in print_tbl
    writer.writerow(row)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 87: ordinal not in range(128)
```

Do you have any idea on what I can do to get it running? It seems to have trouble printing the table after gathering the data. I can get it running on Windows though.

Thanks in advance!

**Comment by Napo2k** [comment]
This is odd, I have a Mac and I was able to run it without trouble yesterday night (~12 hours ago?)

**Comment by kaito1410** [comment]
> Hey there,
> 
> I'm getting the following error trying to run the main.py on both Ubuntu and macOS.
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 101, in <module>
>     main()
>   File "main.py", line 98, in main
>     print_tbl(results_tbl, args.filename, args.allsub, args.yahoo, args.csv)
>   File "/app/auto-dd/AutoDD.py", line 378, in print_tbl
>     writer.writerow(row)
> UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 87: ordinal not in range(128)
> ```
> 
> Do you have any idea on what I can do to get it running? It seems to have trouble printing the table after gathering the data. I can get it running on Windows though.
> 
> Thanks in advance!

I would double check if you have python3 installed and running. Python3 by default encodes string in Utf-8 which shouldn't have this issue. Report back if it's not fixed and I can try to set the encoding manually.

**Comment by garygrossgarten** [comment]
It's working on my Mac now. Thanks for your help!
