### ISSUE TITLE
    from psaw import PushshiftAPI ImportError: No module named psaw

### ISSUE THREAD

**Issue by gmct05** [kaito1410/AutoDD_Rev2#16]
Hi, I have a mac, everything is working until I run_auto_dd. sh and get this error:
    from psaw import PushshiftAPI
ImportError: No module named psaw
I did isntall all requirements multiple times and have python 3. 

thank you!

**Comment by Napo2k** [comment]
Did you also source the virtual environment, before running run_auto_dd.sh? 
I am working on an improvement for that so it's done automatically, but for now, as part of the execution of install_requirements.sh, a virtual environment is created in a folder called .env
So, these steps should work
```
./install_requirements.sh
source .env/bin/activate
./run_auto_dd.sh
```

**Comment by gmct05** [comment]
that worked perfectly, thank you!

**Comment by Napo2k** [comment]
I will make sure to add that to the readme and _then_ close this ticket!

**Comment by Napo2k** [comment]
@kaito1410 https://github.com/kaito1410/AutoDD_Rev2/pull/17

**Comment by kaito1410** [comment]
Merged! Thanks guys.
