### ISSUE TITLE
Table Columns Incorrect

### ISSUE THREAD

**Issue by TheSwindler44** [kaito1410/AutoDD_Rev2#18]
`python3 main.py --allsub`

Maybe I am missing something in the documentation but I don't believe the numbers in specific columns are adding up correctly. For example, the price of ZOM has never been 186. (It looks like price is under Industry???)

Is this a bug?

<img width="2119" alt="Screen Shot 2021-01-13 at 3 17 10 PM" src="https://user-images.githubusercontent.com/36936042/104505942-aecad480-55b2-11eb-97e7-7283238014e8.png">

**Comment by kaito1410** [comment]
Yes that looks like a bug, will fix it shortly

**Comment by kaito1410** [comment]
Should be fixed now!
