### ISSUE TITLE
Returning Empty Tables

### ISSUE THREAD

**Issue by TheSwindler44** [kaito1410/AutoDD_Rev2#23]
I am not sure what happened. The program was working perfectly until I tried to use it today. Now it just returns nothing. I attempted a new install and it still reproduced the same result. There are no error logs so it's a little difficult to isolate the problem.

<img width="2096" alt="Screen Shot 2021-01-27 at 12 24 46 PM" src="https://user-images.githubusercontent.com/36936042/106029180-d5047000-609a-11eb-9d60-95417c6337cc.png">

Has Reddit changed something on their end?

**Comment by kaito1410** [comment]
Looks like pushshift (psaw) isn't returning any results from reddit. Maybe give it a few hours and see if it's working again.

**Comment by kaito1410** [comment]
Looks like it's working again! closed

**Comment by TheSwindler44** [comment]
quick question, are these results delayed?

I found a site that gives the pushshift current status. The site shows comments delayed by over 6 hours and submissions by 1 hour. 

https://www.reveddit.com/info/

**Comment by kaito1410** [comment]
This could be a possible issue if submission times are delayed by a significant amount of time. The script only searches submissions and not comments. If it's consistently delayed by > 1 hour, let me know and I can try switching to praw (but will need a reddit account to use)
