### ISSUE TITLE
fiftyDayAverage not returned by yahoo, causes error

### ISSUE THREAD

**Issue by gobbedy** [kaito1410/AutoDD_Rev2#26]
I just tried the code, it's awesome!

Although I just tried to run this command:
```main.py --interval 2 --sub wallstreetbets```

And got this error output:
```
Traceback (most recent call last):
  File "C:\Users\guillaume\PycharmProjects\AutoDD_Rev2\main.py", line 101, in <module>
    main()
  File "C:\Users\guillaume\PycharmProjects\AutoDD_Rev2\main.py", line 92, in main
    results_tbl = getQuickStats(results_tbl)
  File "C:\Users\guillaume\PycharmProjects\AutoDD_Rev2\AutoDD.py", line 491, in getQuickStats
    if avg50day > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

After some debugging I was able to narrow it down to the ticker "WIN" for which yahoo does not return 'fiftyDayAverage'. I wrote a little standalone to isolate the error:
```
from yahooquery import Ticker
ticker=Ticker('WIN')
data=ticker.summary_detail.get('WIN')
if data.get('fiftyDayAverage') is None:
    print("Houston...")
```

I doubt "WIN" was meant as a stock ticker in the reddit submission, but regardless, it is a valid ticker, so this error should not occur?

In the meantime I added "WIN" to the list of banned words locally. Works as a temp fix.

**Comment by kaito1410** [comment]
Fixed, thanks! https://github.com/kaito1410/AutoDD_Rev2/pull/28
