### ISSUE TITLE
PSAW 3 days behind!

### ISSUE THREAD

**Issue by TheSwindler44** [kaito1410/AutoDD_Rev2#32]
Just wanted to let you know that PSAW has been unresponsive for around 2 days.

https://www.reveddit.com/info/

**Comment by kaito1410** [comment]
Looking into alternatives!

**Comment by gobbedy** [comment]
The guy maintaining pushshift has explained that they're transitioning to AWS, and it may cause outages
https://twitter.com/jasonbaumgartne/status/1357048169415274509

He also mentioned his goal is to be live on AWS in mid Feb
https://twitter.com/jasonbaumgartne/status/1355040354345562114

I wouldn't worry too much if there are outages for the next little while

**Comment by kaito1410** [comment]
Praw option added, the script now uses praw by default.
