### ISSUE TITLE
issue with rocket count?

### ISSUE THREAD

**Issue by gobbedy** [kaito1410/AutoDD_Rev2#33]
Hello,

rockets seem to be counted in an odd way. Let's take an example. Suppose a reddit submission has the following title:
"PLEASE BUY AAPL, MSFT, GME NOW"

then for that submission you would have
```
rocket_dict['PLEASE'] += 6
rocket_dict['BUY'] += 6
rocket_dict['AAPL'] += 6
rocket_dict['MSFT'] += 6
rocket_dict['GME'] += 6
rocket_dict['NOW'] += 6
```

Shouldn't it be ```+=1``` for each one?

Could you please clarify what rockets count?

PS. I should have finished the refactored code by Monday or so if you're interested. Speedup is in the order of 100x when there are many tickers.

**Comment by kaito1410** [comment]
Awesome news gobbedy, looking forward to your changes. Your understanding of the rocket count is mostly correct. Since there's no way to tell which ticker the rockets are ment for, all rockets for the submission will count towards the ticker that appear in the submission. For example the score 6 would mean there are 6 rocket emojis in that submission.

**Comment by kaito1410** [comment]
The rocket count idea is more of a "meme" play, as people sometimes put a lot of rocket emojis in their post. The rocket count shows the user how many rocket emoji did the ticker get across all of the posts in the subreddit.

**Comment by gobbedy** [comment]
oooh got it. i didn't know about the rocket meme, thanks for explaining!

is there no way to count instances of the rocket emoji itself?

**Comment by gobbedy** [comment]
ooh my bad that's what you're counting! I totally misread the code. i thought you were counting instances where the ticker appears. that makes so much more sense now!!

explains the confusion in the previous issue too. this is all just me being dumb haha
