### ISSUE TITLE
redundancy?

### ISSUE THREAD

**Issue by gobbedy** [kaito1410/AutoDD_Rev2#34]
Am I right that ```or row[1][1] >= min_val``` is redundant in the code below?
```
tbl = [row for row in tbl if row[1][0] >= min_val or row[1][1] >= min_val]
```
If I'm not mistaken ```row[1][0]``` is the total score (prev + current) for the ticker, and ```row[1][1]``` is the current score.

I'm removing the redundant part in my version of the code, just making sure I haven't misunderstood something?

**Comment by kaito1410** [comment]
Yea that part is redundant. Good catch. I guess we should keep row[1][0] >= min_val since we should be filtering by total score > min value

**Comment by gobbedy** [comment]
cool thanks!
